### PR TITLE
Unity starter template

### LINKED ISSUE #4: Upload Template Unity Project
Upload a template project with a basic scene, what it generates for you

### PR DESCRIPTION
**Pull request by Jodiiiiiiii**
includes a single empty scene. should be able to be opened and edited by everyone

### CODE REVIEW

**Review by rileycleavenger — APPROVED** [review]
LGTM! Having this template ready for everyone to branch off and work on will be really helpful

**Comment by rileycleavenger** [comment]
The issue is the merge conflict with the gitignore, but should be easy to solve bc the gitignore in main is like 1 or 2 lines iirc

**Comment by Jodiiiiiiii** [comment]
I merged main back in I added the one .DS_store line to the end of the .gitignore. I honestly don't know how gitignores work entirely but if someone could let me know if that works then we are good to merge

**Review by rileycleavenger — APPROVED** [review]
The gitignore addition is correct, LGTM!

**Pull request merged**
